"Input validation"
DenWouk/eCommerce-Application pull request #29
Opened 2023-08-18 17:47 UTC by tetlisna

Reverts DenWouk/eCommerce-Application#28

2023-08-18 17:47 UTC, zakalupali89 commented
All good!!

2023-08-18 17:53 UTC, zakalupali89 requested changes
Check postal validation

2023-08-19 09:30 UTC, DenWouk reviewed
All good!

2023-08-19 09:30 UTC, zakalupali89 approved these changes
All good!

2023-08-19 09:31 UTC, merged